services:
  it-tools:
    image: sharevb/it-tools:latest@sha256:dc76937113a0a22f86cc3711e7a1c87937cb4d78a0fc048ccbfaad1bc571fdce
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ./tools-filter.json:/usr/share/nginx/html/tools-filter.json
      - ./external-tools.json:/usr/share/nginx/html/external-tools.json
      - ./home.custom.md:/usr/share/nginx/html/home.custom.md
    ports:
      - 8080:8080